<?php declare(strict_types=1);

/**
 * Kreblu Configuration
 *
 * This file is generated by the installer. Do not edit unless you know what you're doing.
 * For Docker/CI environments, you can override these values with environment variables.
 *
 * @see https://kreblu.org/docs/configuration
 */

// == Database Settings ==
define('KB_DB_HOST',   'localhost');
define('KB_DB_PORT',   3306);
define('KB_DB_NAME',   'kreblu');
define('KB_DB_USER',   'your_db_user');
define('KB_DB_PASS',   'your_db_password');
define('KB_DB_PREFIX', 'kb_');

// == Site URL ==
// No trailing slash. Example: https://example.com
define('KB_SITE_URL', 'http://localhost');

// == Security Keys ==
// Change these to unique random strings. The installer generates these automatically.
// You can regenerate them at: https://kreblu.org/secret-key-generator
define('KB_AUTH_KEY',   'put-your-unique-phrase-here');
define('KB_SECURE_KEY', 'put-your-unique-phrase-here');
define('KB_NONCE_KEY',  'put-your-unique-phrase-here');
define('KB_NONCE_SALT', 'put-your-unique-phrase-here');

// == Debug Mode ==
// Set to true for development. NEVER true in production.
define('KB_DEBUG', false);

// == Environment ==
// 'production', 'staging', or 'development'
define('KB_ENV', 'production');
